export const LOGIN_WITH_OAUTH_LOADING = 'LOGIN_WITH_OAUTH_LOADING';
export const LOGIN_WITH_OAUTH_SUCCESS = 'LOGIN_WITH_OAUTH_SUCCESS';
export const LOGIN_WITH_OAUTH_FAIL = 'LOGIN_WITH_OAUTH_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const LOGIN_WITH_EMAIL_LOADING = 'LOGIN_WITH_EMAIL_LOADING';
export const LOGIN_WITH_EMAIL_SUCCESS = 'LOGIN_WITH_EMAIL_SUCCESS';
export const LOGIN_WITH_EMAIL_FAIL = 'LOGIN_WITH_EMAIL_FAIL';

export const REGISTER_WITH_EMAIL_LOADING = 'REGISTER_WITH_EMAIL_LOADING';
export const REGISTER_WITH_EMAIL_SUCCESS = 'REGISTER_WITH_EMAIL_SUCCESS';
export const REGISTER_WITH_EMAIL_FAIL = 'REGISTER_WITH_EMAIL_FAIL';

export const ME_LOADING = 'ME_LOADING';
export const ME_SUCCESS = 'ME_SUCCESS';
export const ME_FAIL = 'ME_FAIL';

export const GET_FEATURE = 'GET_FEATURE';
export const GET_PROFILE = 'GET_PROFILE';

export const GET_USERS_LOADING = 'GET_USERS_LOADING';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const GET_PROFILE_LOADING = 'GET_PROFILE_LOADING';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';

export const EDIT_USER_LOADING = 'EDIT_USER_LOADING';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL';

export const DELETE_USER_LOADING = 'DELETE_USER_LOADING';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

export const GET_MY_EXPENSES_LOADING = 'GET_MY_EXPENSES_LOADING';
export const GET_MY_EXPENSES_SUCCESS = 'GET_MY_EXPENSES_SUCCESS';
export const GET_MY_EXPENSES_FAIL = 'GET_MY_EXPENSES_FAIL';

export const GET_MY_EXPENSES_BY_USER_ID_LOADING = 'GET_MY_EXPENSES_BY_USER_ID_LOADING';
export const GET_MY_EXPENSES_BY_USER_ID_SUCCESS = 'GET_MY_EXPENSES_BY_USER_ID_SUCCESS';
export const GET_MY_EXPENSES_BY_USER_ID_FAIL = 'GET_MY_EXPENSES_BY_USER_ID_FAIL';

export const ADD_MY_EXPENSE_LOADING = 'ADD_MY_EXPENSE_LOADING';
export const ADD_MY_EXPENSE_SUCCESS = 'ADD_MY_EXPENSE_SUCCESS';
export const ADD_MY_EXPENSE_FAIL = 'ADD_MY_EXPENSE_FAIL';

export const DELETE_MY_EXPENSE_LOADING = 'DELETE_MY_EXPENSE_LOADING';
export const DELETE_MY_EXPENSE_SUCCESS = 'DELETE_MY_EXPENSE_SUCCESS';
export const DELETE_MY_EXPENSE_FAIL = 'DELETE_MY_EXPENSE_FAIL';

export const EDIT_MY_EXPENSE_LOADING = 'EDIT_MY_EXPENSE_LOADING';
export const EDIT_MY_EXPENSE_SUCCESS = 'EDIT_MY_EXPENSE_SUCCESS';
export const EDIT_MY_EXPENSE_FAIL = 'EDIT_MY_EXPENSE_FAIL';
export const CLEAR_MY_EXPENSE_ERROR = 'CLEAR_MY_EXPENSE_ERROR';

export const GET_CATEGORY_LOADING = 'GET_CATEGORY_LOADING';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAIL = 'GET_CATEGORY_FAIL';

export const GET_CATEGORY_BY_ID_LOADING = 'GET_CATEGORY_BY_ID_LOADING';
export const GET_CATEGORY_BY_ID_SUCCESS = 'GET_CATEGORY_BY_ID_SUCCESS';
export const GET_CATEGORY_BY_ID_FAIL = 'GET_CATEGORY_BY_ID_FAIL';

export const ADD_CATEGORY_LOADING = 'ADD_CATEGORY_LOADING';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAIL = 'ADD_CATEGORY_FAIL';